name: Test SSH Connection

on:
  push:
    branches:
      - main
      - dev

jobs:
  ssh-test:
    runs-on: self-hosted  # your self-hosted runner

    steps:
      - name: Test SSH Connection to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "SSH connection successful!"
            uname -a
