name: Build, Push and Deploy on Merge

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Development Image (for dev branch)
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            sadeeee/nest-ci-pipeline-development:latest
            sadeeee/nest-ci-pipeline-development:${{ github.sha }}

      - name: Build and Push Production Image (for main branch)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            sadeeee/nest-ci-pipeline-production:latest
            sadeeee/nest-ci-pipeline-production:${{ github.sha }}

      - name: Deploy to Linux server
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            IMAGE_NAME="sadeeee/nest-ci-pipeline-$(if [ '${{ github.ref }}' == 'refs/heads/main' ]; then echo 'production'; else echo 'development'; fi):latest"
            echo "Pulling $IMAGE_NAME"
            docker pull $IMAGE_NAME
            echo "Stopping and removing existing container..."
            docker stop nest-ci || true
            docker rm nest-ci || true
            echo "Starting container..."
            docker run -d --restart unless-stopped --name nest-ci -p 3000:3000 $IMAGE_NAME
